version: '3'

services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda
    ports:
      - "127.0.0.1:8080:8080"

  capython:
    image: keyweeusr/capython:1.0.0-3.9.7-slim-buster
    container_name: capython
    volumes:
      - ./sample-requirements.txt:/app/sample-requirements.txt
    environment:
      - CAPYTHON_REQUIREMENTS=/app/sample-requirements.txt
